name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: yarn
      - name: Deploy to Android
        uses: NishanthShankar/codepush-action@master
        with:
          args: release-react -a dogehouse/dogehouse-1 -d deployment
        env:
          APPCENTER_ACCESS_TOKEN: ${{ secrets.CODEPUSH_ANDROID_ACCESS_KEY }}
      - name: Deploy to Ios
        uses: NishanthShankar/codepush-action@master
        with:
          args: release-react -a dogehouse/dogehouse -d deployment --plist-file=ios/dogehouseTvMobile/Info.plist
        env:
          APPCENTER_ACCESS_TOKEN: ${{ secrets.CODEPUSH_IOS_ACCESS_KEY  }}
